/**
 * F314 — the default crop keeps the PHOTOGRAPH out, measured in two
 * dimensions and asserted against GROUND TRUTH.
 *
 * The seven layouts in `ink-profiles.json` use a flat grey placeholder where
 * a real page has a photograph, so none of this was exercised: the box on the
 * walk's own page spanned the header band AND the photo placeholder while the
 * copy above it said the photo does not leave the browser.
 *
 * `photo-masks.json` is generated by `e2e/make-crop-fixtures.mjs` in a real
 * Chromium: three layouts with a PROCEDURAL photo-like texture (value noise +
 * soft blobs + a gradient — not a face, not a downloaded image, not a real
 * person), each recording its OWN rectangles. The assertions below are
 * against those rectangles, not against whatever the algorithm produced.
 */

import { readFileSync } from 'fs';
import { join } from 'path';

import {
  EDGE_THRESHOLD,
  RULE_MAX_PX,
  SOLID_DENSITY,
  SOLID_MIN_AREA,
  columnBlocks,
  defaultCropFromMask,
  edgeInkFromMask,
  inkRuns,
  profileIn,
  solidInsideOf,
  textColumnSpan,
  type Block,
  type EdgeMask,
  type Rect,
} from '../crop';

interface Layout {
  width: number;
  height: number;
  /** run-length encoded per row, starting with a ZERO run */
  rle: number[][];
  rects: { photo: Rect | null; header: Rect | null; values: Rect[] };
}

const FIXTURE = JSON.parse(
  readFileSync(join(__dirname, 'fixtures', 'photo-masks.json'), 'utf8'),
) as { edgeThreshold: number; layouts: Record<string, Layout> };

function unpack(layout: Layout): EdgeMask {
  const bits = new Uint8Array(layout.width * layout.height);
  for (let y = 0; y < layout.height; y += 1) {
    let x = 0;
    let on = 0;
    for (const run of layout.rle[y]) {
      if (on) for (let k = 0; k < run; k += 1) bits[y * layout.width + x + k] = 1;
      x += run;
      on ^= 1;
    }
  }
  return { width: layout.width, height: layout.height, bits };
}

const CASES = Object.entries(FIXTURE.layouts);
const overlaps = (a: Rect, b: Rect) =>
  a.x < b.x + b.width && b.x < a.x + a.width && a.y < b.y + b.height && b.y < a.y + a.height;
/**
 * Is every EDGE PIXEL of `inner` inside `outer`?
 *
 * Not "is the rectangle inside the rectangle": the fixture records a value's
 * rectangle from the font metrics, which are generous above the cap height
 * and below the baseline. What matters is whether any of the value's INK
 * falls outside the box — that is what "the value was cut off" means, and
 * it is what the extractor would suffer from.
 */
const inkOutside = (mask: EdgeMask, inner: Rect, outer: Rect): number => {
  let out = 0;
  for (let y = inner.y; y < inner.y + inner.height; y += 1) {
    if (y < 0 || y >= mask.height) continue;
    for (let x = inner.x; x < inner.x + inner.width; x += 1) {
      if (x < 0 || x >= mask.width) continue;
      if (!mask.bits[y * mask.width + x]) continue;
      const insideBox =
        x >= outer.x && x < outer.x + outer.width && y >= outer.y && y < outer.y + outer.height;
      if (!insideBox) out += 1;
    }
  }
  return out;
};

describe('the photo fixtures are real measurements with real ground truth', () => {
  it('covers the three layouts, each with a photo and four value rows', () => {
    expect(CASES.map(([n]) => n).sort()).toEqual([
      'photo_dominant_corner.png',
      'photo_left_header.png',
      'photo_right.png',
    ]);
    for (const [name, layout] of CASES) {
      expect({ name, photo: Boolean(layout.rects.photo) }).toEqual({ name, photo: true });
      expect(layout.rects.values).toHaveLength(4);
    }
  });

  it('was measured with the threshold the panel uses', () => {
    expect(FIXTURE.edgeThreshold).toBe(EDGE_THRESHOLD);
  });

  it('unpacks to a mask with ink in it — a blank mask would make this vacuous', () => {
    for (const [name, layout] of CASES) {
      const mask = unpack(layout);
      const ink = mask.bits.reduce((a: number, b: number) => a + b, 0);
      expect({ name, hasInk: ink > 1000 }).toEqual({ name, hasInk: true });
      expect(mask.bits).toHaveLength(layout.width * layout.height);
    }
  });
});

describe('a photograph is told from writing by EDGE DENSITY', () => {
  const classified = CASES.map(([name, layout]) => {
    const mask = unpack(layout);
    const plan = defaultCropFromMask(mask);
    return { name, layout, mask, plan };
  });

  it('separates them by SIZE and DENSITY together, not by density alone', () => {
    // Density alone is scale-blind: one line of 17 px text splits into word
    // blocks whose ink fills 0.5–0.6 of their own tiny extent, which is why
    // `SOLID_MIN_AREA` exists. So the claim under test is the DECISION, and
    // the evidence for the density constant is taken over blocks of
    // comparable size — the only comparison in which it means anything.
    const big = classified
      .flatMap(({ plan }) => plan.blocks)
      .filter((b) => b.kind !== 'rule' && b.width * b.height >= SOLID_MIN_AREA);
    const text = big.filter((b) => b.kind === 'text').map((b) => b.density);
    const solid = big.filter((b) => b.kind === 'solid').map((b) => b.density);
    expect(text.length).toBeGreaterThan(0);
    expect(solid.length).toBeGreaterThan(0);
    // MEASURED at comparable size: text 0.15–0.22, photographs 0.92–0.94.
    expect(Math.max(...text)).toBeLessThan(SOLID_DENSITY);
    expect(Math.min(...solid)).toBeGreaterThan(SOLID_DENSITY);
    // and the threshold sits in the empty middle rather than close to either
    expect(SOLID_DENSITY - Math.max(...text)).toBeGreaterThan(0.1);
    expect(Math.min(...solid) - SOLID_DENSITY).toBeGreaterThan(0.1);
  });

  it('never calls a block of TEXT a photograph, whatever its density', () => {
    // The decision, checked against ground truth: no block that overlaps a
    // birth-detail VALUE may be classified solid, or the box would be moved
    // off the very thing it exists to enclose.
    for (const { name, layout, plan } of classified) {
      const wrong = plan.blocks
        .filter((b) => b.kind === 'solid')
        .filter((b) => layout.rects.values.some((v) => overlaps(b, v)));
      expect({ name, textCalledAPhotograph: wrong.length }).toEqual({
        name,
        textCalledAPhotograph: 0,
      });
    }
  });

  it('finds the photograph where the fixture says it is', () => {
    for (const { name, layout, plan } of classified) {
      const solids = plan.blocks.filter((b) => b.kind === 'solid');
      const photo = layout.rects.photo!;
      const found = solids.some((b) => overlaps(b, photo));
      expect({ name, foundThePhoto: found }).toEqual({ name, foundThePhoto: true });
    }
  });

  it('calls a 2 px vertical line a RULE, standing on its own', () => {
    // The fixtures' photo border touches the photograph, so it never becomes
    // a block of its own there. This is the branch on its own: a 2 px line
    // with a gutter each side. Without the rule test it would be measured as
    // a column of content — 100% dense, and only its small area keeping it
    // out of the `solid` class.
    const width = 20;
    const height = 40;
    const bits = new Uint8Array(width * height);
    for (let y = 5; y < 35; y += 1) {
      bits[y * width + 9] = 1;
      bits[y * width + 10] = 1;
    }
    const mask: EdgeMask = { width, height, bits };
    const blocks = columnBlocks(mask, { x: 0, y: 0, width, height });
    expect(blocks).toHaveLength(1);
    expect(blocks[0]).toMatchObject({ kind: 'rule', x: 9, width: 2 });
    // and a rule is never the thing the box opens on
    expect(textColumnSpan(blocks)).toBeNull();
  });

  it('calls a 1 px HORIZONTAL line a rule too', () => {
    // A full-width hairline is 900 px wide and one pixel tall: wide enough to
    // pass the width test, and no more a block of content than the vertical
    // border is.
    const width = 60;
    const height = 20;
    const bits = new Uint8Array(width * height);
    for (let x = 4; x < 56; x += 1) bits[10 * width + x] = 1;
    const mask: EdgeMask = { width, height, bits };
    const blocks = columnBlocks(mask, { x: 0, y: 0, width, height });
    expect(blocks.every((block) => block.kind === 'rule')).toBe(true);
  });

  it('treats a 1-2 px border as a RULE, never as a column of content', () => {
    for (const { plan } of classified) {
      for (const block of plan.blocks) {
        if (block.width <= RULE_MAX_PX) expect(block.kind).toBe('rule');
        if (block.kind === 'text') expect(block.width).toBeGreaterThan(RULE_MAX_PX);
      }
    }
  });
});

describe('THE DEFAULT BOX DOES NOT CONTAIN THE PHOTOGRAPH (ASTRAL-331)', () => {
  it.each(CASES)('%s: zero overlap with the photo rectangle', (_name, layout) => {
    const plan = defaultCropFromMask(unpack(layout));
    expect(overlaps(plan.rect, layout.rects.photo!)).toBe(false);
  });

  it.each(CASES)('%s: no ink on any boundary of the box', (_name, layout) => {
    const mask = unpack(layout);
    const plan = defaultCropFromMask(mask);
    expect(edgeInkFromMask(mask, plan.rect)).toMatchObject({ any: false });
  });

  it.each(CASES)('%s: NO ink of any birth-detail value falls outside the box', (name, layout) => {
    // All four values sit in one text column on every layout, so "where the
    // layout allows" is all four. If a layout is ever added where a value is
    // on the far side of the photograph, this is the assertion that will say
    // so — rather than a box that quietly swallowed the photo to reach it.
    const mask = unpack(layout);
    const plan = defaultCropFromMask(mask);
    const cut = layout.rects.values
      .map((v, i) => ({ row: i, outside: inkOutside(mask, v, plan.rect) }))
      .filter((r) => r.outside > 0);
    expect({ name, cut }).toEqual({ name, cut: [] });
  });

  it.each(CASES)('%s: the box is strictly smaller than the page', (_name, layout) => {
    const plan = defaultCropFromMask(unpack(layout));
    expect(plan.rect.width * plan.rect.height).toBeLessThan(layout.width * layout.height);
  });

  it('leaves the HEADER out whole rather than slicing the name (priority 3 loses)', () => {
    // photo_left_header puts the name in a full-width banner ABOVE the photo.
    // The columns that exclude the photo would cut that banner in half, so
    // the banner is dropped ENTIRELY and the name comes back `missing` — a
    // field the user types in five seconds, rather than a sliced one that
    // reads as a fact (F308).
    const layout = FIXTURE.layouts['photo_left_header.png'];
    const plan = defaultCropFromMask(unpack(layout));
    expect(overlaps(plan.rect, layout.rects.header!)).toBe(false);
    // and the name is simply not read — `missing`, which the user types,
    // rather than "Asha" with the rest of it outside the box
    const mask = unpack(layout);
    expect(inkOutside(mask, layout.rects.header!, plan.rect)).toBeGreaterThan(0);
  });
});

describe('the segmentation, as arithmetic', () => {
  it('splits at gutters and joins across a single blank line', () => {
    //          0  1  2  3  4  5  6  7  8  9
    const v = [0, 3, 0, 4, 0, 0, 5, 0, 0, 7];
    expect(inkRuns(v)).toEqual([
      { start: 1, end: 3 },
      { start: 6, end: 6 },
      { start: 9, end: 9 },
    ]);
  });

  it('is empty on a blank profile', () => {
    expect(inkRuns([0, 0, 0])).toEqual([]);
  });

  it('takes a profile INSIDE a rectangle, in the rectangle\'s own coordinates', () => {
    const mask: EdgeMask = { width: 4, height: 3, bits: new Uint8Array([
      0, 0, 0, 0,
      0, 1, 1, 0,
      0, 0, 0, 0,
    ]) };
    const inner = profileIn(mask, { x: 1, y: 1, width: 2, height: 2 });
    expect(inner.rows).toEqual([2, 0]);
    expect(inner.cols).toEqual([1, 1]);
  });

  it('a full-width band elsewhere cannot fill the columns of this band', () => {
    // The 1-D failure, as arithmetic: row 0 is a full-width header. Measured
    // over the WHOLE image every column has ink; measured inside the band
    // below it, only the two columns that really carry text do.
    const width = 6;
    const bits = new Uint8Array(width * 4);
    for (let x = 0; x < width; x += 1) bits[x] = 1; // the header band
    bits[3 * width + 1] = 1;
    bits[3 * width + 2] = 1; // two columns of "text" three rows down
    const mask: EdgeMask = { width, height: 4, bits };
    expect(profileIn(mask, { x: 0, y: 0, width, height: 4 }).cols).toEqual([1, 2, 2, 1, 1, 1]);
    expect(profileIn(mask, { x: 0, y: 3, width, height: 1 }).cols).toEqual([0, 1, 1, 0, 0, 0]);
  });

  it('picks the LARGER text side when a solid block sits between two', () => {
    const block = (x: number, width: number, kind: Block['kind'], ink: number): Block => ({
      x,
      y: 0,
      width,
      height: 10,
      kind,
      density: kind === 'solid' ? 0.9 : 0.1,
      ink,
    });
    const span = textColumnSpan([
      block(0, 40, 'text', 100),
      block(50, 60, 'solid', 5000),
      block(120, 80, 'text', 400),
    ]);
    expect(span).toEqual({ x: 120, width: 80 });
  });

  it('a rule between two text blocks does not break them apart', () => {
    const block = (x: number, width: number, kind: Block['kind'], ink: number): Block => ({
      x,
      y: 0,
      width,
      height: 10,
      kind,
      density: 0.1,
      ink,
    });
    const span = textColumnSpan([
      block(0, 40, 'text', 100),
      block(45, 2, 'rule', 0),
      block(50, 40, 'text', 100),
    ]);
    expect(span).toEqual({ x: 0, width: 90 });
  });

  it('has nothing to offer when every block is solid', () => {
    expect(
      textColumnSpan([
        { x: 0, y: 0, width: 50, height: 10, kind: 'solid', density: 0.9, ink: 900 },
      ]),
    ).toBeNull();
  });
});

describe('the live photo warning has something to warn about', () => {
  it('reports a solid block the user has dragged the box over', () => {
    const layout = FIXTURE.layouts['photo_left_header.png'];
    const mask = unpack(layout);
    const plan = defaultCropFromMask(mask);
    // the default box is clear…
    expect(solidInsideOf(plan.blocks, plan.rect)).toBeNull();
    // …and a box dragged across the photograph is not
    const overPhoto: Rect = {
      x: layout.rects.photo!.x,
      y: layout.rects.photo!.y,
      width: layout.rects.photo!.width,
      height: layout.rects.photo!.height,
    };
    expect(solidInsideOf(plan.blocks, overPhoto)).not.toBeNull();
  });

  it('the exact edge-ink check has no 1-D false alarm', () => {
    // Ink on the same ROW as the box, but outside its columns. The 1-D
    // profile called that "touching"; the mask does not.
    const width = 10;
    const bits = new Uint8Array(width * 6);
    bits[2 * width + 0] = 1; // ink far to the left, on the box's top row
    const mask: EdgeMask = { width, height: 6, bits };
    const box: Rect = { x: 4, y: 2, width: 3, height: 2 };
    expect(edgeInkFromMask(mask, box).any).toBe(false);
    // and ink INSIDE the box's own extent on that row is reported
    bits[2 * width + 5] = 1;
    expect(edgeInkFromMask(mask, box).top).toBe(true);
  });
});
